AWSTemplateFormatVersion: "2010-09-09"
Description: HHV2 App

Parameters:
  artifactStack:
    Type: String
    Default: "hhv2-artifacts"

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref AWS::StackName
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      UserPoolConfig:
        UserPoolId: !Ref UserPool
        AwsRegion: !Ref AWS::Region
        DefaultAction: DENY
  GraphQLApiSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !Ref GraphQLApi
      DefinitionS3Location: !Sub
        - "${artifactLocation}${file}"
        - "artifactLocation": !ImportValue
            "Fn::Sub": "${artifactStack}-ArtifactBucketName"
          "file": "schema.graphql"
